Chat:
    enabled: true
    Colors: true
    Compatibility: false
    Prefix:
        Avatar: "[Avatar] "
        Air: "[Airbender] "
        Earth: "[Earthbender] "
        Fire: "[Firebender] "
        Water: "[Waterbender] "
    Color:
        Avatar: "LIGHT_PURPLE"
        Air: "GRAY"
        Earth: "GREEN"
        Fire: "RED"
        Water: "BLUE"

Bending:
    Damage:
        AirSwipe: 1
        EarthBlast: 7
        WaterManipulation: 7
    Option:
        EarthBendable: [STONE, CLAY, COAL_ORE, DIAMOND_ORE, DIRT, GOLD_ORE, GRASS, GRAVEL, IRON_ORE, LAPIS_ORE, NETHERRACK, REDSTONE_ORE, SAND, SANDSTONE]