name: Bending
main: main.Bending
version: 1.0.8
commands:
    bending:
        description: Chooses the many features of Bending.
        usage: |
             /<command> choose [element]
             /<command> display [element]
             /<command> bind [ability]
             /<command> display
             /<command> clear
permissions:
  bending.air.*:
    description: Allows all air bending.
    children:
      bending.air.AirSwipe: true
      bending.air.AirBubble: true
      bending.air.AirShield: true
      bending.air.AirSuction: true
      bending.air.Speed: true
      bending.air.Tornado: true
      bending.air.AirBlast: true
      bending.air.Passive: true
#      bending.air.AirSpout: false
#      bending.air.AirBurst: false
      bending.air.AirScooter: true
  bending.fire.*:
    description: Allows all fire bending.
    children:
      bending.fire.Blaze: true
      bending.fire.Extinguish: true
      bending.fire.Fireball: true
      bending.fire.FireJet: true
      bending.fire.FireBlast: true
      bending.fire.HeatMelt: true
      bending.fire.Passive: true
      bending.fire.Illumination: true
      bending.fire.WallOfFire: true
      bending.fire.Lightning: true
  bending.water.*:
    description: Allows all water bending.
    children:
      bending.water.FreezeMelt: true
      bending.water.HealingWaters: true
      bending.water.Plantbending: true
      bending.water.WalkOnWater: true
      bending.water.WaterBubble: true
      bending.water.WaterManipulation: true
      bending.water.WaterWall: true
      bending.water.Wave: true
      bending.water.Passive: true
      bending.water.WaterSpout: true
 #     bending.water.Bloodbending: false
  bending.earth.*:
    description: Allows all earth bending.
    children:
      bending.earth.Catapult: true
      bending.earth.CompactColumn: true
      bending.earth.EarthBlast: true
      bending.earth.RaiseEarth: true
      bending.earth.EarthGrab: true
      bending.earth.EarthTunnel: true
      bending.earth.Collapse: true
      bending.earth.Passive: true
      bending.earth.Tremorsense: true
      bending.earth.EarthArmor: true
#      bending.earth.Shockwave: false
  bending.chiblocking.*:
    description: Allows all chiblocking abilities.
    children:
      bending.chiblocking.RapidPunch: true
      bending.chiblocking.HighJump: true
  bending.*:
    description: Allows all bending.
    children:
      bending.earth.*: true
      bending.water.*: true
      bending.fire.*: true
      bending.air.*: true
      
  bending.admin:
    description: Allows all commands.
    children:
      bending.admin.avatarstate: true
      bending.admin.remove: true
      bending.admin.reload: true
      bending.admin.permaremove: true
      bending.command.choose: true
      bending.admin.rechoose: true
      bending.admin.choose: true
      bending.admin.add: true
      bending.command.displayelement: true
      bending.commnd.clear: true
      bending.command.display: true
      bending.command.bind: true
      bending.fire.Lightning: false
      bending.water.Bloodbending: true
      bending.command.toggle: true
      
  bending.command:
    description: Allows all user commands.
    children:
      bending.command.choose: true
      bending.command.displayelement: true
      bending.commnd.clear: true
      bending.command.display: true
      bending.command.bind: true
      bending.command.help: true
      bending.command.toggle: true

  bending.air.AirSwipe:
    description: Allows the use of AirSwipe.
    default: true
  bending.air.AirBubble:
    description: Allows the use of AirBubble.
    default: true
  bending.air.Passive:
    description: Allows the use of AirPassive.
    default: true
  bending.air.AirShield:
    description: Allows the use of AirShield.
    default: true
  bending.air.AirSuction:
    description: Allows the use of AirSuction.
    default: true
  bending.air.AirSpout:
    description: Allows the use of AirSpout.
    default: true
  bending.air.AirScooter:
    description: Allows the use of AirScooter.
    default: true
  bending.air.Speed:
    description: Allows the use of Speed.
    default: true
  bending.air.Tornado:
    description: Allows the use of Tornado.
    default: true
  bending.air.AirBlast:
    description: Allows the use of AirBlast.
    default: true
  bending.air.AirBurst:
    description: Allows the use of AirBurst.
#    default: true
    default: false
  bending.air.AirSpout:
    description: Allows the use of AirSpout.
#    default: true
    default: false
  bending.fire.Blaze:
    description: Allows the use of Blaze.
    default: true
  bending.fire.Extinguish:
    description: Allows the use of Extinguish.
    default: true
  bending.fire.Fireball:
    description: Allows the use of Fireball.
    default: true
  bending.fire.FireJet:
    description: Allows the use of FireJet.
    default: true
  bending.fire.FireBlast:
    description: Allows the use of FireBlast
    default: true
  bending.fire.HeatMelt:
    description: Allows the use of HeatMelt.
    default: true
  bending.fire.Passive:
    description: Allows the use of Passive.
    default: true
  bending.fire.Illumination:
    description: Allows the use of Illumination.
    default: true
  bending.fire.WallOfFire:
    description: Allows the use of WallOfFire.
    default: true
  bending.fire.Lightning:
    description: Allows the use of Lightning.
    default: true
  bending.water.FreezeMelt:
    description: Allows the use of Freeze.
    default: true
  bending.water.HealingWaters:
    description: Allows the use of HealingWaters.
    default: true
  bending.water.Plantbending:
    description: Allows the use of Plantbending.
    default: true
  bending.water.WalkOnWater:
    description: Allows the use of WalkOnWater.
    default: true
  bending.water.WaterBubble:
    description: Allows the use of WaterBubble.
    default: true
  bending.water.WaterManipulation:
    description: Allows the use of WaterManipulation.
    default: true
  bending.water.Passive:
    description: Allows the use of WaterPassive.
    default: true
  bending.water.WaterSpout:
    description: Allows the use of WaterSpout.
    default: true
  bending.water.WaterWall:
    description: Allows the use of WaterWall.
    default: true
  bending.water.Wave:
    description: Allows the use of Wave.
    default: true
  bending.water.Bloodbending:
    description: Allows the use of Bloodbending.
    default: op
  bending.earth.Catapult:
    description: Allows the use of Catapult.
    default: true
  bending.earth.CompactColumn:
    description: Allows the use of CompactColumn.
    default: true
  bending.earth.EarthBlast:
    description: Allows the use of EarthBlast.
    default: true
  bending.earth.RaiseEarth:
    description: Allows the use of RaiseEarth.
    default: true
  bending.earth.Passive:
    description: Allows the use of EarthPassive.
    default: true
  bending.earth.EarthTunnel:
    description: Allows the use of EarthTunnel.
    default: true
  bending.earth.Collapse:
    description: Allows the use of PatchTheEarth.
    default: true
  bending.earth.EarthGrab:
    description: Allows the use of EarthGrab.
    default: true
  bending.earth.Tremorsense:
    description: Allows the use of Tremorsense.
    default: true 
  bending.earth.Shockwave:
    description: Allows the use of Shockwave.
#    default: true
    default: false
  bending.earth.EarthArmor:
    description: Allows the use of EarthArmor
    default: true
  bending.chiblocking.RapidPunch:
    description: Allows the use of RapidPunch
    default: true
  bending.chiblocking.HighJump:
    description: Allows the use of HighJump
    default: true
  bending.AvatarState:
    description: Allows the use of AvatarState.
    default: op
  bending.admin.avatarstate: 
    description: Allows the use of AvatarState.
    default: op 
  bending.admin.remove: 
    description: Allows the use of /bending remove <player>
    default: op
  bending.admin.reload:
    description: Allows the use of /bending reload
    default: op
  bending.admin.permaremove:
    description: Allows the use of /bending  permaremove <player>
    default: op
  bending.command.choose:
    description: Allows the use of /bending choose <element>
    default: true
  bending.admin.rechoose:
    description: Allows the use of /bending choose <element> after choosing one.
    default: op
  bending.admin.choose:
    description: Allows the use of /bending choose <player> <element>
    default: op
  bending.admin.add: 
    description: Allows the use of /bending add <element>
    default: op
  bending.command.displayelement: 
    description: Allows the use of /bending display <element>
    default: true
  bending.commnd.clear: 
    description: Allows the use of /bending clear 
    default: true
  bending.command.display:
    description: Allows the use of /bending display
    default: true
  bending.command.bind:
    description: Allows the use of /bending bind <ability>
    default: true
  bending.command.help:
    description: Allows the use of /bending help
    default: true
  bending.command.toggle:
    description: Allows the use of /bending toggle
    default: true
  bending.avatar:
    description: Give the avatar prefix.
    default: op
  bending.command.import:
    default: op
  bending.chiblocker.FastPunch:
    default: op
  bending.water.IceSpike:
    default: true
  bending.chiblocker.Paralyze:
    default: op
